name = "Advanced Integrated Radio System"
author = "Asaayu"
prefix = "airs"
mainprefix = "z"

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

[version]
major = 0
minor = 0
patch = 0
build = 0

[files]
include = [
    "version_check.txt",
    "*.dll",
    "LICENSE",
]
exclude = [
    "**/*.psd",
    "**/*.png",
]